# Generated by Django 5.0.1 on 2024-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='type',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned')], max_length=10),
        ),
    ]
